volumes:
  postgres_data:

services:
  only-db:
    container_name: postgres-only-db
    image: postgres:latest
    ports:
      - '5426:5432'
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_BASE}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_BASE}" ]
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 10s

    volumes:
      - postgres_data:/var/lib/postgresql/data/


  nginx:
    container_name: nginx-server
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/user/backend/static:/usr/share/nginx/html/static
    depends_on:
      - backend
