

services:
    postgres:
        container_name: postgres
        image: postgres:16-alpine
        expose:
            - "5432"
        restart: unless-stopped
        environment:
            POSTGRES_USER: 'some_user'
            POSTGRES_PASSWORD: 'my_secret_password'
            POSTGRES_DB: 'mycloud-database'
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U some_user -d mycloud-database"]
            interval: 10s
            timeout: 15s
            retries: 5
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    backend:
        container_name: backend
        build:
            context: ./backend
            args:
                DB_HOST: 'postgres'
                DB_PORT: 5432
                DB_BASE: 'mycloud-database'
                DB_USER: 'some_user'
                DB_PASS: 'my_secret-password'
                APP_DEBUG: false
                SECRET_KEY: 'django-insecure-z6$$*7$9*r_d%xgek=y=u3f80@fj1mbq=y3*mj6k-ik_0#*v!w'
                ALLOWED_HOSTS: 'localhost,185.10.45.10'
                FRONTEND_URL: 'https://185.10.45.10'
                SERVER_NAME: '185.10.45.10'
                ADMIN_PASSWORD: 'adminNEWadmin'
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - static_volume:/app/staticfiles
            - storage_volume:/app/storage
        depends_on:
            - postgres

    frontend:
        container_name: frontend
        build:
            context: ./frontend                # Путь к вашему фронтенду (Vite)
        ports:
            - "5173:5173"                      # Порт вашего приложения Vite
        depends_on:
            - backend

    nginx:
        container_name: nginx
        build:
            context: ./frontend                # Убедитесь, что путь правильный для вашего Nginx
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/ssl/:/etc/ssl/
            - static_volume:/staticfiles
            - storage_volume:/storage
        depends_on:
            - backend
            - postgres

volumes:
    postgres_data:
    static_volume:
    storage_volume:
