services:
    postgres:
        container_name: postgres
        image: postgres:16-alpine
        expose:
            - "5432"
        restart: unless-stopped
        environment:
            POSTGRES_USER: 'some_user'
            POSTGRES_PASSWORD: 'my_secret_password'
            POSTGRES_DB: 'mycloud-database'
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d mycloud-database" ]
            interval: 10s
            timeout: 15s
            retries: 5
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    backend:
        container_name: backend
        build:
            context: ./backend
            args:
                DB_HOST: 'postgres'
                DB_PORT: 5432
                DB_BASE: 'mycloud-database'
                DB_USER: 'some_user'
                DB_PASS: 'my_secret-password'
                APP_DEBUG: false
                ALLOWED_HOSTS: 'localhost,185.10.45.10'
                FRONTEND_URL: 'https://185.10.45.10'
                SERVER_NAME: '185.10.45.10'
                ADMIN_PASSWORD: 'adminNEWadmin'
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - static_volume:/app/staticfiles
            - storage_volume:/app/storage
        expose:
            - 8000
        depends_on:
            - postgres

    frontend:
        build:
            context: ./frontend                # Путь к вашему фронтенду (Vite)
        container_name: frontend
        ports:
            - "5173:5173"                      # Порт вашего приложения Vite
        depends_on:
            - backend

    nginx:
        container_name: proxy
        build: ./frontend
        restart: always
        ports:
            - '80:80'
            - '443:443'
        command: sh -c "chmod +x /home/run.sh && /home/run.sh"
        volumes:
            - static_volume:/staticfiles
            - storage_volume:/storage
            - ./nginx:/home
        depends_on:
            - backend
            - postgres

volumes:
    postgres_data:
    static_volume:
    storage_volume:
