version: '3.9'

networks:
    cloudnet:

services:
    postgres-db:
        image: postgres
        container_name: postgres-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5426:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./logs:/var/postgres_log
        env_file:
            - .env
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
            interval: 10s
            timeout: 15s
            retries: 5
            start_period: 10s
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G
        networks:
            - cloudnet

volumes:
    postgres-data:
