name: Deploy Backend Application

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: mycloud-env

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      .github/workflows/backend.yaml
                      backend
                      nginx
                      docker-compose.yaml

            - name: Set up SSH with credentials
              uses: actions/setup-ssh@v2
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  ssh-host: ${{ secrets.SSH_HOST }}
                  ssh-user: ${{ secrets.SSH_USER }}

            - name: Install Docker Compose on server
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo apt-get update && sudo apt-get install -y docker-compose"

            - name: Copy Docker Compose file to server
              uses: sftp-git/action@v4
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: 22
                  source_dir: .
                  dest_dir: /home/${{ secrets.SSH_USER }}

            - name: Deploy Docker Compose application on server
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker-compose -f /home/${{ secrets.SSH_USER }}/docker-compose.yml up -d"
