name: Deploy Backend Application

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: mycloud-env

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      backend/
                      nginx/
                      static/
                      storage/

            - name: Set up SSH with credentials
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Add server to known hosts
              run: |
                mkdir -p ~/.ssh
                if ssh-keygen -F ${{ secrets.SSH_HOST }} > /dev/null; then
                ssh-keygen -R ${{ secrets.SSH_HOST }}
                fi
                ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Clear target directory on server
              run: |
                ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
                  sudo rm -rf /home/${{ secrets.SSH_USER }}/* \
                "

#            - name: Install OpenSSL and generate self-signed certificate
#              run: |
#                ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
#                    sudo apt-get update && \
#                    sudo apt-get install -y openssl && \
#                    sudo mkdir -p /home/${{ secrets.SSH_USER }}/nginx/ssl && \
#                    sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
#                      -keyout /home/${{ secrets.SSH_USER }}/nginx/ssl/cert.key \
#                      -out /home/${{ secrets.SSH_USER }}/nginx/ssl/cert.crt \
#                      -subj '/CN=${{ secrets.SSH_HOST }}/O=MyCloud/C=RU' \
#                "
#            - name: Fix permissions for nginx directory
#              run: |
#                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
#                    sudo chown -R ${{ secrets.SSH_USER }}:$${{ secrets.SSH_USER }} /home/${{ secrets.SSH_USER }}/nginx && \
#                    sudo chmod -R 755 /home/${{ secrets.SSH_USER }}/nginx \
#                  "

            - name: Install Docker Compose on server
              run: |
                ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
                  sudo apt-get update && sudo apt-get install -y docker-compose
                "

            - name: Copy Docker Compose file to server
              uses: appleboy/scp-action@v0.1.0
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PASSWORD }}
                source: "."
                target: "/home/${{ secrets.SSH_USER }}"

            - name: Create .env file on server
              run: |
                ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
                  echo 'DB_BASE=${{ secrets.DB_BASE }}' > /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'DB_HOST=${{ secrets.DB_HOST }}' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'DB_PORT=${{ secrets.DB_PORT }}' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'DB_USER=${{ secrets.DB_USER }}' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'DB_PASS=${{ secrets.DB_PASS }}' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }}' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'SECRET_KEY=${{ secrets.SECRET_KEY }}' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'DEBUG=${{ secrets.DEBUG }}' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'BACKEND_URL=https://185.10.45.10' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'SERVER_NAME=185.10.45.10' >> /home/${{ secrets.SSH_USER }}/.env && \
                  echo 'FRONTEND_URL=https://berson969.github.io' >> /home/${{ secrets.SSH_USER }}/.env
                "

            - name: Copy .env file to another directory on server
              run: |
                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
                    sudo cp /home/${{ secrets.SSH_USER }}/.env /home/${{ secrets.SSH_USER }}/backend/.env \
                  "

            - name: Deploy Docker Compose application on server
              run: |
                ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
                  cd /home/${{ secrets.SSH_USER }} && sudo docker-compose up -d --force-recreate --remove-orphans
                 "
