name: Deploy Backend Application

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: mycloud-env

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      .github/workflows/backend.yaml
                      backend
                      nginx
                      docker-compose.yaml
                    
            - name: List files in the workspace
              run: ls -R

            - name: Set up SSH with credentials
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
                  
            - name: Add server to known hosts
              run: |
                mkdir -p ~/.ssh
                ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts     

            - name: Install Docker Compose on server
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo apt-get update && sudo apt-get install -y docker-compose"

            - name: Copy Docker Compose file to server
              uses: appleboy/scp-action@v0.1.0
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PASSWORD }}
                source: "docker-compose.yml"
                target: "/home/${{ secrets.SSH_USER }}/docker-compose.yml"


            - name: Verify file existence
              run: |
                ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -l /home/${{ secrets.SSH_USER }}/docker-compose.yml"
          
            - name: Deploy Docker Compose application on server
              run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/${{ secrets.SSH_USER }} && docker-compose up -d"
