name: Deploy React Frontend

on:
    push:
        branches: [main]
permissions:
    contents: write


jobs:
    build-frontend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies & Build React app
              working-directory: frontend
              env:
                  VITE_BASE_QUERY_URL: http://localhost
                  VITE_BASE_URL: /diplom-mycloud/
              run: |
                  npm install
                  npm run build

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: frontend/dist
                  branch: gh-pages
                  target-folder: "."
